// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: comm_service.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Input         string                 `protobuf:"bytes,1,opt,name=input,proto3" json:"input,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestRequest) Reset() {
	*x = TestRequest{}
	mi := &file_comm_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestRequest) ProtoMessage() {}

func (x *TestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_comm_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestRequest.ProtoReflect.Descriptor instead.
func (*TestRequest) Descriptor() ([]byte, []int) {
	return file_comm_service_proto_rawDescGZIP(), []int{0}
}

func (x *TestRequest) GetInput() string {
	if x != nil {
		return x.Input
	}
	return ""
}

type TestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resp          string                 `protobuf:"bytes,1,opt,name=resp,proto3" json:"resp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestResponse) Reset() {
	*x = TestResponse{}
	mi := &file_comm_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestResponse) ProtoMessage() {}

func (x *TestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_comm_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestResponse.ProtoReflect.Descriptor instead.
func (*TestResponse) Descriptor() ([]byte, []int) {
	return file_comm_service_proto_rawDescGZIP(), []int{1}
}

func (x *TestResponse) GetResp() string {
	if x != nil {
		return x.Resp
	}
	return ""
}

type RequestVoteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestVoteRequest) Reset() {
	*x = RequestVoteRequest{}
	mi := &file_comm_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestVoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestVoteRequest) ProtoMessage() {}

func (x *RequestVoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_comm_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestVoteRequest.ProtoReflect.Descriptor instead.
func (*RequestVoteRequest) Descriptor() ([]byte, []int) {
	return file_comm_service_proto_rawDescGZIP(), []int{2}
}

func (x *RequestVoteRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RequestVoteRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type RequestVoteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VoteGiven     bool                   `protobuf:"varint,1,opt,name=voteGiven,proto3" json:"voteGiven,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestVoteResponse) Reset() {
	*x = RequestVoteResponse{}
	mi := &file_comm_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestVoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestVoteResponse) ProtoMessage() {}

func (x *RequestVoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_comm_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestVoteResponse.ProtoReflect.Descriptor instead.
func (*RequestVoteResponse) Descriptor() ([]byte, []int) {
	return file_comm_service_proto_rawDescGZIP(), []int{3}
}

func (x *RequestVoteResponse) GetVoteGiven() bool {
	if x != nil {
		return x.VoteGiven
	}
	return false
}

type AppendEntriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendEntriesRequest) Reset() {
	*x = AppendEntriesRequest{}
	mi := &file_comm_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendEntriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendEntriesRequest) ProtoMessage() {}

func (x *AppendEntriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_comm_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendEntriesRequest.ProtoReflect.Descriptor instead.
func (*AppendEntriesRequest) Descriptor() ([]byte, []int) {
	return file_comm_service_proto_rawDescGZIP(), []int{4}
}

type AppendEntriedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendEntriedResponse) Reset() {
	*x = AppendEntriedResponse{}
	mi := &file_comm_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendEntriedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendEntriedResponse) ProtoMessage() {}

func (x *AppendEntriedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_comm_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendEntriedResponse.ProtoReflect.Descriptor instead.
func (*AppendEntriedResponse) Descriptor() ([]byte, []int) {
	return file_comm_service_proto_rawDescGZIP(), []int{5}
}

type ReplicateLogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicateLogRequest) Reset() {
	*x = ReplicateLogRequest{}
	mi := &file_comm_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicateLogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicateLogRequest) ProtoMessage() {}

func (x *ReplicateLogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_comm_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicateLogRequest.ProtoReflect.Descriptor instead.
func (*ReplicateLogRequest) Descriptor() ([]byte, []int) {
	return file_comm_service_proto_rawDescGZIP(), []int{6}
}

type ReplicateLogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicateLogResponse) Reset() {
	*x = ReplicateLogResponse{}
	mi := &file_comm_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicateLogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicateLogResponse) ProtoMessage() {}

func (x *ReplicateLogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_comm_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicateLogResponse.ProtoReflect.Descriptor instead.
func (*ReplicateLogResponse) Descriptor() ([]byte, []int) {
	return file_comm_service_proto_rawDescGZIP(), []int{7}
}

type SnapshotChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotChunk) Reset() {
	*x = SnapshotChunk{}
	mi := &file_comm_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotChunk) ProtoMessage() {}

func (x *SnapshotChunk) ProtoReflect() protoreflect.Message {
	mi := &file_comm_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotChunk.ProtoReflect.Descriptor instead.
func (*SnapshotChunk) Descriptor() ([]byte, []int) {
	return file_comm_service_proto_rawDescGZIP(), []int{8}
}

type SnapshotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotResponse) Reset() {
	*x = SnapshotResponse{}
	mi := &file_comm_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotResponse) ProtoMessage() {}

func (x *SnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_comm_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotResponse.ProtoReflect.Descriptor instead.
func (*SnapshotResponse) Descriptor() ([]byte, []int) {
	return file_comm_service_proto_rawDescGZIP(), []int{9}
}

type CommandRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandRequest) Reset() {
	*x = CommandRequest{}
	mi := &file_comm_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandRequest) ProtoMessage() {}

func (x *CommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_comm_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandRequest.ProtoReflect.Descriptor instead.
func (*CommandRequest) Descriptor() ([]byte, []int) {
	return file_comm_service_proto_rawDescGZIP(), []int{10}
}

type CommandResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandResponse) Reset() {
	*x = CommandResponse{}
	mi := &file_comm_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandResponse) ProtoMessage() {}

func (x *CommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_comm_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandResponse.ProtoReflect.Descriptor instead.
func (*CommandResponse) Descriptor() ([]byte, []int) {
	return file_comm_service_proto_rawDescGZIP(), []int{11}
}

type AddServerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddServerRequest) Reset() {
	*x = AddServerRequest{}
	mi := &file_comm_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddServerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddServerRequest) ProtoMessage() {}

func (x *AddServerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_comm_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddServerRequest.ProtoReflect.Descriptor instead.
func (*AddServerRequest) Descriptor() ([]byte, []int) {
	return file_comm_service_proto_rawDescGZIP(), []int{12}
}

type AddServerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddServerResponse) Reset() {
	*x = AddServerResponse{}
	mi := &file_comm_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddServerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddServerResponse) ProtoMessage() {}

func (x *AddServerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_comm_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddServerResponse.ProtoReflect.Descriptor instead.
func (*AddServerResponse) Descriptor() ([]byte, []int) {
	return file_comm_service_proto_rawDescGZIP(), []int{13}
}

type RemoveServerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveServerRequest) Reset() {
	*x = RemoveServerRequest{}
	mi := &file_comm_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveServerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveServerRequest) ProtoMessage() {}

func (x *RemoveServerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_comm_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveServerRequest.ProtoReflect.Descriptor instead.
func (*RemoveServerRequest) Descriptor() ([]byte, []int) {
	return file_comm_service_proto_rawDescGZIP(), []int{14}
}

type RemoveServerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveServerResponse) Reset() {
	*x = RemoveServerResponse{}
	mi := &file_comm_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveServerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveServerResponse) ProtoMessage() {}

func (x *RemoveServerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_comm_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveServerResponse.ProtoReflect.Descriptor instead.
func (*RemoveServerResponse) Descriptor() ([]byte, []int) {
	return file_comm_service_proto_rawDescGZIP(), []int{15}
}

type StateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StateRequest) Reset() {
	*x = StateRequest{}
	mi := &file_comm_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateRequest) ProtoMessage() {}

func (x *StateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_comm_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateRequest.ProtoReflect.Descriptor instead.
func (*StateRequest) Descriptor() ([]byte, []int) {
	return file_comm_service_proto_rawDescGZIP(), []int{16}
}

type StateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StateResponse) Reset() {
	*x = StateResponse{}
	mi := &file_comm_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateResponse) ProtoMessage() {}

func (x *StateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_comm_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateResponse.ProtoReflect.Descriptor instead.
func (*StateResponse) Descriptor() ([]byte, []int) {
	return file_comm_service_proto_rawDescGZIP(), []int{17}
}

var File_comm_service_proto protoreflect.FileDescriptor

const file_comm_service_proto_rawDesc = "" +
	"\n" +
	"\x12comm_service.proto\x12\rcomm_services\"#\n" +
	"\vTestRequest\x12\x14\n" +
	"\x05input\x18\x01 \x01(\tR\x05input\"\"\n" +
	"\fTestResponse\x12\x12\n" +
	"\x04resp\x18\x01 \x01(\tR\x04resp\">\n" +
	"\x12RequestVoteRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\"3\n" +
	"\x13RequestVoteResponse\x12\x1c\n" +
	"\tvoteGiven\x18\x01 \x01(\bR\tvoteGiven\"\x16\n" +
	"\x14AppendEntriesRequest\"\x17\n" +
	"\x15AppendEntriedResponse\"\x15\n" +
	"\x13ReplicateLogRequest\"\x16\n" +
	"\x14ReplicateLogResponse\"\x0f\n" +
	"\rSnapshotChunk\"\x12\n" +
	"\x10SnapshotResponse\"\x10\n" +
	"\x0eCommandRequest\"\x11\n" +
	"\x0fCommandResponse\"\x12\n" +
	"\x10AddServerRequest\"\x13\n" +
	"\x11AddServerResponse\"\x15\n" +
	"\x13RemoveServerRequest\"\x16\n" +
	"\x14RemoveServerResponse\"\x0e\n" +
	"\fStateRequest\"\x0f\n" +
	"\rStateResponse2T\n" +
	"\vTestService\x12E\n" +
	"\bTestThis\x12\x1a.comm_services.TestRequest\x1a\x1b.comm_services.TestResponse\"\x002\xca\x01\n" +
	"\x12RequestVoteService\x12V\n" +
	"\vRequestVote\x12!.comm_services.RequestVoteRequest\x1a\".comm_services.RequestVoteResponse\"\x00\x12\\\n" +
	"\rAppendEntries\x12#.comm_services.AppendEntriesRequest\x1a$.comm_services.AppendEntriedResponse\"\x002r\n" +
	"\x15LogReplicationService\x12Y\n" +
	"\fReplicateLog\x12\".comm_services.ReplicateLogRequest\x1a#.comm_services.ReplicateLogResponse\"\x002n\n" +
	"\x16InstallSnapshotService\x12T\n" +
	"\x0fInstallSnapshot\x12\x1c.comm_services.SnapshotChunk\x1a\x1f.comm_services.SnapshotResponse\"\x00(\x012h\n" +
	"\x14ClientRequestService\x12P\n" +
	"\rClientRequest\x12\x1d.comm_services.CommandRequest\x1a\x1e.comm_services.CommandResponse\"\x002\xc7\x01\n" +
	"\x18ClusterManagementService\x12P\n" +
	"\tAddServer\x12\x1f.comm_services.AddServerRequest\x1a .comm_services.AddServerResponse\"\x00\x12Y\n" +
	"\fRemoveServer\x12\".comm_services.RemoveServerRequest\x1a#.comm_services.RemoveServerResponse\"\x002[\n" +
	"\x10StateQueryServic\x12G\n" +
	"\bGetState\x12\x1b.comm_services.StateRequest\x1a\x1c.comm_services.StateResponse\"\x00B\x03Z\x01/b\x06proto3"

var (
	file_comm_service_proto_rawDescOnce sync.Once
	file_comm_service_proto_rawDescData []byte
)

func file_comm_service_proto_rawDescGZIP() []byte {
	file_comm_service_proto_rawDescOnce.Do(func() {
		file_comm_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_comm_service_proto_rawDesc), len(file_comm_service_proto_rawDesc)))
	})
	return file_comm_service_proto_rawDescData
}

var file_comm_service_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_comm_service_proto_goTypes = []any{
	(*TestRequest)(nil),           // 0: comm_services.TestRequest
	(*TestResponse)(nil),          // 1: comm_services.TestResponse
	(*RequestVoteRequest)(nil),    // 2: comm_services.RequestVoteRequest
	(*RequestVoteResponse)(nil),   // 3: comm_services.RequestVoteResponse
	(*AppendEntriesRequest)(nil),  // 4: comm_services.AppendEntriesRequest
	(*AppendEntriedResponse)(nil), // 5: comm_services.AppendEntriedResponse
	(*ReplicateLogRequest)(nil),   // 6: comm_services.ReplicateLogRequest
	(*ReplicateLogResponse)(nil),  // 7: comm_services.ReplicateLogResponse
	(*SnapshotChunk)(nil),         // 8: comm_services.SnapshotChunk
	(*SnapshotResponse)(nil),      // 9: comm_services.SnapshotResponse
	(*CommandRequest)(nil),        // 10: comm_services.CommandRequest
	(*CommandResponse)(nil),       // 11: comm_services.CommandResponse
	(*AddServerRequest)(nil),      // 12: comm_services.AddServerRequest
	(*AddServerResponse)(nil),     // 13: comm_services.AddServerResponse
	(*RemoveServerRequest)(nil),   // 14: comm_services.RemoveServerRequest
	(*RemoveServerResponse)(nil),  // 15: comm_services.RemoveServerResponse
	(*StateRequest)(nil),          // 16: comm_services.StateRequest
	(*StateResponse)(nil),         // 17: comm_services.StateResponse
}
var file_comm_service_proto_depIdxs = []int32{
	0,  // 0: comm_services.TestService.TestThis:input_type -> comm_services.TestRequest
	2,  // 1: comm_services.RequestVoteService.RequestVote:input_type -> comm_services.RequestVoteRequest
	4,  // 2: comm_services.RequestVoteService.AppendEntries:input_type -> comm_services.AppendEntriesRequest
	6,  // 3: comm_services.LogReplicationService.ReplicateLog:input_type -> comm_services.ReplicateLogRequest
	8,  // 4: comm_services.InstallSnapshotService.InstallSnapshot:input_type -> comm_services.SnapshotChunk
	10, // 5: comm_services.ClientRequestService.ClientRequest:input_type -> comm_services.CommandRequest
	12, // 6: comm_services.ClusterManagementService.AddServer:input_type -> comm_services.AddServerRequest
	14, // 7: comm_services.ClusterManagementService.RemoveServer:input_type -> comm_services.RemoveServerRequest
	16, // 8: comm_services.StateQueryServic.GetState:input_type -> comm_services.StateRequest
	1,  // 9: comm_services.TestService.TestThis:output_type -> comm_services.TestResponse
	3,  // 10: comm_services.RequestVoteService.RequestVote:output_type -> comm_services.RequestVoteResponse
	5,  // 11: comm_services.RequestVoteService.AppendEntries:output_type -> comm_services.AppendEntriedResponse
	7,  // 12: comm_services.LogReplicationService.ReplicateLog:output_type -> comm_services.ReplicateLogResponse
	9,  // 13: comm_services.InstallSnapshotService.InstallSnapshot:output_type -> comm_services.SnapshotResponse
	11, // 14: comm_services.ClientRequestService.ClientRequest:output_type -> comm_services.CommandResponse
	13, // 15: comm_services.ClusterManagementService.AddServer:output_type -> comm_services.AddServerResponse
	15, // 16: comm_services.ClusterManagementService.RemoveServer:output_type -> comm_services.RemoveServerResponse
	17, // 17: comm_services.StateQueryServic.GetState:output_type -> comm_services.StateResponse
	9,  // [9:18] is the sub-list for method output_type
	0,  // [0:9] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_comm_service_proto_init() }
func file_comm_service_proto_init() {
	if File_comm_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_comm_service_proto_rawDesc), len(file_comm_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   7,
		},
		GoTypes:           file_comm_service_proto_goTypes,
		DependencyIndexes: file_comm_service_proto_depIdxs,
		MessageInfos:      file_comm_service_proto_msgTypes,
	}.Build()
	File_comm_service_proto = out.File
	file_comm_service_proto_goTypes = nil
	file_comm_service_proto_depIdxs = nil
}
