// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: date_service.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DateService_GetCurrentDate_FullMethodName = "/dateservice.DateService/GetCurrentDate"
	DateService_GetUserInfo_FullMethodName    = "/dateservice.DateService/GetUserInfo"
	DateService_Greet_FullMethodName          = "/dateservice.DateService/Greet"
)

// DateServiceClient is the client API for DateService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DateServiceClient interface {
	// GetCurrentDate returns the current date and time
	GetCurrentDate(ctx context.Context, in *DateRequest, opts ...grpc.CallOption) (*DateResponse, error)
	// GetUserInfo returns the user information
	GetUserInfo(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*UserResponse, error)
	Greet(ctx context.Context, in *GreetRequest, opts ...grpc.CallOption) (*GreetResponse, error)
}

type dateServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDateServiceClient(cc grpc.ClientConnInterface) DateServiceClient {
	return &dateServiceClient{cc}
}

func (c *dateServiceClient) GetCurrentDate(ctx context.Context, in *DateRequest, opts ...grpc.CallOption) (*DateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DateResponse)
	err := c.cc.Invoke(ctx, DateService_GetCurrentDate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dateServiceClient) GetUserInfo(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*UserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserResponse)
	err := c.cc.Invoke(ctx, DateService_GetUserInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dateServiceClient) Greet(ctx context.Context, in *GreetRequest, opts ...grpc.CallOption) (*GreetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GreetResponse)
	err := c.cc.Invoke(ctx, DateService_Greet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DateServiceServer is the server API for DateService service.
// All implementations must embed UnimplementedDateServiceServer
// for forward compatibility.
type DateServiceServer interface {
	// GetCurrentDate returns the current date and time
	GetCurrentDate(context.Context, *DateRequest) (*DateResponse, error)
	// GetUserInfo returns the user information
	GetUserInfo(context.Context, *UserRequest) (*UserResponse, error)
	Greet(context.Context, *GreetRequest) (*GreetResponse, error)
	mustEmbedUnimplementedDateServiceServer()
}

// UnimplementedDateServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDateServiceServer struct{}

func (UnimplementedDateServiceServer) GetCurrentDate(context.Context, *DateRequest) (*DateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCurrentDate not implemented")
}
func (UnimplementedDateServiceServer) GetUserInfo(context.Context, *UserRequest) (*UserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserInfo not implemented")
}
func (UnimplementedDateServiceServer) Greet(context.Context, *GreetRequest) (*GreetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Greet not implemented")
}
func (UnimplementedDateServiceServer) mustEmbedUnimplementedDateServiceServer() {}
func (UnimplementedDateServiceServer) testEmbeddedByValue()                     {}

// UnsafeDateServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DateServiceServer will
// result in compilation errors.
type UnsafeDateServiceServer interface {
	mustEmbedUnimplementedDateServiceServer()
}

func RegisterDateServiceServer(s grpc.ServiceRegistrar, srv DateServiceServer) {
	// If the following call pancis, it indicates UnimplementedDateServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DateService_ServiceDesc, srv)
}

func _DateService_GetCurrentDate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DateServiceServer).GetCurrentDate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DateService_GetCurrentDate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DateServiceServer).GetCurrentDate(ctx, req.(*DateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DateService_GetUserInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DateServiceServer).GetUserInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DateService_GetUserInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DateServiceServer).GetUserInfo(ctx, req.(*UserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DateService_Greet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GreetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DateServiceServer).Greet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DateService_Greet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DateServiceServer).Greet(ctx, req.(*GreetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DateService_ServiceDesc is the grpc.ServiceDesc for DateService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DateService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dateservice.DateService",
	HandlerType: (*DateServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCurrentDate",
			Handler:    _DateService_GetCurrentDate_Handler,
		},
		{
			MethodName: "GetUserInfo",
			Handler:    _DateService_GetUserInfo_Handler,
		},
		{
			MethodName: "Greet",
			Handler:    _DateService_Greet_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "date_service.proto",
}
