// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: proto/date_service.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DateRequest) Reset() {
	*x = DateRequest{}
	mi := &file_proto_date_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DateRequest) ProtoMessage() {}

func (x *DateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_date_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DateRequest.ProtoReflect.Descriptor instead.
func (*DateRequest) Descriptor() ([]byte, []int) {
	return file_proto_date_service_proto_rawDescGZIP(), []int{0}
}

type DateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CurrentDate   string                 `protobuf:"bytes,1,opt,name=current_date,json=currentDate,proto3" json:"current_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DateResponse) Reset() {
	*x = DateResponse{}
	mi := &file_proto_date_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DateResponse) ProtoMessage() {}

func (x *DateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_date_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DateResponse.ProtoReflect.Descriptor instead.
func (*DateResponse) Descriptor() ([]byte, []int) {
	return file_proto_date_service_proto_rawDescGZIP(), []int{1}
}

func (x *DateResponse) GetCurrentDate() string {
	if x != nil {
		return x.CurrentDate
	}
	return ""
}

type UserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserRequest) Reset() {
	*x = UserRequest{}
	mi := &file_proto_date_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRequest) ProtoMessage() {}

func (x *UserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_date_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRequest.ProtoReflect.Descriptor instead.
func (*UserRequest) Descriptor() ([]byte, []int) {
	return file_proto_date_service_proto_rawDescGZIP(), []int{2}
}

type UserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserLogin     string                 `protobuf:"bytes,1,opt,name=user_login,json=userLogin,proto3" json:"user_login,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserResponse) Reset() {
	*x = UserResponse{}
	mi := &file_proto_date_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserResponse) ProtoMessage() {}

func (x *UserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_date_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserResponse.ProtoReflect.Descriptor instead.
func (*UserResponse) Descriptor() ([]byte, []int) {
	return file_proto_date_service_proto_rawDescGZIP(), []int{3}
}

func (x *UserResponse) GetUserLogin() string {
	if x != nil {
		return x.UserLogin
	}
	return ""
}

var File_proto_date_service_proto protoreflect.FileDescriptor

const file_proto_date_service_proto_rawDesc = "" +
	"\n" +
	"\x18proto/date_service.proto\x12\vdateservice\"\r\n" +
	"\vDateRequest\"1\n" +
	"\fDateResponse\x12!\n" +
	"\fcurrent_date\x18\x01 \x01(\tR\vcurrentDate\"\r\n" +
	"\vUserRequest\"-\n" +
	"\fUserResponse\x12\x1d\n" +
	"\n" +
	"user_login\x18\x01 \x01(\tR\tuserLogin2\x9c\x01\n" +
	"\vDateService\x12G\n" +
	"\x0eGetCurrentDate\x12\x18.dateservice.DateRequest\x1a\x19.dateservice.DateResponse\"\x00\x12D\n" +
	"\vGetUserInfo\x12\x18.dateservice.UserRequest\x1a\x19.dateservice.UserResponse\"\x00B\fZ\n" +
	"test/protob\x06proto3"

var (
	file_proto_date_service_proto_rawDescOnce sync.Once
	file_proto_date_service_proto_rawDescData []byte
)

func file_proto_date_service_proto_rawDescGZIP() []byte {
	file_proto_date_service_proto_rawDescOnce.Do(func() {
		file_proto_date_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_date_service_proto_rawDesc), len(file_proto_date_service_proto_rawDesc)))
	})
	return file_proto_date_service_proto_rawDescData
}

var file_proto_date_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_date_service_proto_goTypes = []any{
	(*DateRequest)(nil),  // 0: dateservice.DateRequest
	(*DateResponse)(nil), // 1: dateservice.DateResponse
	(*UserRequest)(nil),  // 2: dateservice.UserRequest
	(*UserResponse)(nil), // 3: dateservice.UserResponse
}
var file_proto_date_service_proto_depIdxs = []int32{
	0, // 0: dateservice.DateService.GetCurrentDate:input_type -> dateservice.DateRequest
	2, // 1: dateservice.DateService.GetUserInfo:input_type -> dateservice.UserRequest
	1, // 2: dateservice.DateService.GetCurrentDate:output_type -> dateservice.DateResponse
	3, // 3: dateservice.DateService.GetUserInfo:output_type -> dateservice.UserResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_date_service_proto_init() }
func file_proto_date_service_proto_init() {
	if File_proto_date_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_date_service_proto_rawDesc), len(file_proto_date_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_date_service_proto_goTypes,
		DependencyIndexes: file_proto_date_service_proto_depIdxs,
		MessageInfos:      file_proto_date_service_proto_msgTypes,
	}.Build()
	File_proto_date_service_proto = out.File
	file_proto_date_service_proto_goTypes = nil
	file_proto_date_service_proto_depIdxs = nil
}
